### ISSUE TITLE
add example command

### ISSUE THREAD

**Issue by dag7dev** [mattn/algia#11]
I am trying to use your client, however it says "string not all lowercase or all uppercase".

I am typing "algia timeline".

Can you provide some simple example in the readme? 

Thanks!

**Comment by mattn** [comment]
do you make your configuration file ?

**Comment by dag7dev** [comment]
> do you make your configuration file ?

of course!

**Comment by mattn** [comment]
As least, your configuration is valid, `algia tl` should work correctly, I think.

**Comment by dag7dev** [comment]
this is my conf file, where wss is a valid nostr instance.

Private Key is like the one I just wrote here, because it's empty (I don't wanna put a private Key).

{
"relays": {
"wss://...": {
"read": true,
"write": true,
"search": true
}
},
"privatekey": "nsecXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}

-------- Original Message --------

**Comment by mattn** [comment]
Can you provide the relay you used ?

**Comment by dag7dev** [comment]
wrote you on nostr :)

**Comment by mattn** [comment]
please file new issue if you still have an issue
