### ISSUE TITLE
Add explicit LICENSE file

### ISSUE THREAD

**Issue by dergigi** [mattn/algia#14]
License is MIT, but it would be great to have an explicit file (as is standard) so GitHub and other tools can pick up on it. 

https://github.com/mattn/algia#license

![Screenshot 2023-09-28 at 14 02 29](https://github.com/mattn/algia/assets/109058/b0afb854-8c3a-4b83-8ee9-095487ed6748)

Thank you.

---

Edit: I mean like this: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by mattn** [comment]
Thank your pointing this, I added LICENSE file.
![image](https://github.com/mattn/algia/assets/10111/4d72ea31-7cd9-47d4-81db-6d7fb63e2400)

**Comment by mattn** [comment]
If you still have an issue, please file new issue. Thanks.
